# Generated by Django 4.1.5 on 2023-02-19 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0003_testimonial_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Активен'),
        ),
    ]
