# Generated by Django 4.1.5 on 2023-02-04 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Оклад')),
                ('tax', models.PositiveSmallIntegerField(blank=True, default=12, null=True, verbose_name='Налог %')),
                ('deductions', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Вычеты')),
                ('alimony', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Алименты %')),
                ('net', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='На руки')),
                ('year', models.PositiveSmallIntegerField(choices=[(1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023)], default=2023, verbose_name='Год')),
                ('month', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default='2', verbose_name='Месяц')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Дата изменения')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers_wage', to='teachers.teacher', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Заработная плата',
                'verbose_name_plural': 'Заработная плата',
                'ordering': ['teacher'],
            },
        ),
    ]
